services:
  postgres:
    image: postgres:latest
    container_name: divine_ai_db
    environment:
      POSTGRES_DB: divine_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
